<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address:' => 'Адрес:',
    'Article added' => '',
    'Company' => '',
    'Contacts' => 'Контакты',
    'Data created' => '',
    'Date create' => '',
    'Date update' => '',
    'E-mail' => '',
    'E-mail:' => 'E-mail:',
    'For partners' => '',
    'ID' => '',
    'Message' => '',
    'Name' => '',
    'New articles' => '',
    'Order ID' => '',
    'Order status' => '',
    'Patients' => '',
    'Pharmvestnik' => '',
    'Phone' => '',
    'Phone:' => 'Телефон',
    'Product ID' => '',
    'Product name' => '',
    'Product price' => '',
    'Product quantity' => '',
    'Product sum' => '',
    'Products' => 'Препараты',
    'Quantity' => '',
    'Research and development' => '',
    'Source: ' => '',
    'Status' => '',
    'Sum' => '',
    'To specialists' => '',
    'User address' => '',
    'User email' => '',
    'User name' => '',
    'User phone' => '',
    'application for partnership' => '',
    'About' => 'О компании',
    'Certificate ' => 'Сертификат ',
    'Email:' => 'Почта:',
    'Home' => 'Главная',
    'Hours:' => 'Часы работы',
    'Mon-Sat 9:00 am to 6:00 pm' => 'Пн.-Пт. с 9:00 до 18:00',
    'Order at apteka.ru' => 'Купить на apteka.ru',
    'see all' => 'подробнее',
];
